version: '3'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=rudget'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
